server:
  port: 8080

user:
  timezone: Asia/Kuwait

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jta:
    enabled: false
  jackson:
    time-zone: Asia/Kuwait
  threads:
    virtual:
      enabled: true
  application:
    name: tap-payment
  sql:
    init:
      platform: postgres
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
      username: default
      password: password
      timeout: 2000
      database: 0
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: true
      group-id: payment_consumer_group
      auto-offset-reset: earliest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring:
           json:
             trusted:
               packages: '*'
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# application-dev.yml

logging:
  file:
    path: ./logs
    error:
      file: ./logs/error.log
