server:
  port: 8080

user:
  timezone: Asia/Kuwait

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jta:
    enabled: false
  jackson:
    time-zone: Asia/Kuwait
  threads:
    virtual:
      enabled: true
  application:
    name: tap-payment
  sql:
    init:
      platform: postgres

# application-dev.yml

logging:
  file:
    path: ./logs
    error:
      file: ./logs/error.log

# OpenTelemetry
management:
  observations:
    annotations:
      enabled: true
  info:
    os:
      enabled: true
  tracing:
    sampling:
      probability: 1.0
