server:
  port: 8080

app:
  errorPath: ./logs

user:
  timezone: Asia/Kuwait

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: password
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
  jackson:
    time-zone: Asia/Kuwait
  threads:
    virtual:
      enabled: true
  application:
    name: tap-payment
  sql:
    init:
      platform: postgres

# application-dev.yml

logging:
  file:
    path: ./logs
