# application-dev.yml

logging:
  file:
    path: ./logs
apm:
  newrelic:
    license: ${NEW_RELIC_LISENCE_KEY}
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: postgres
    password: password
